version: '2'

networks:
    bibbox-default-network:
      external: true
      
services:

  §§INSTANCE-xnat:
    image: bibbox/xnatweb
    container_name:  §§INSTANCE-xnat
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-xnat-db:xnat-db
    ports:
      - "§§PORT:80"
    depends_on:
      - §§INSTANCE-xnat-db
      - §§INSTANCE-xnat-data
    volumes_from: 
      - §§INSTANCE-xnat-data
    environment:   
       DB_HOST: xnat-db
       DB_NAME: xnat
       DB_USER: xnat
       DB_PASSWORD: §§POSTGRES_PASSWORD

  §§INSTANCE-xnat-db:
    build: ./images/postgres/
    container_name: §§INSTANCE-xnat-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      -  POSTGRES_PASSWORD=§§POSTGRES_PASSWORD
    volumes_from: 
      - §§INSTANCE-seeddms-data
    depends_on:
      - §§INSTANCE-seeddms-data

  §§INSTANCE-xnat-data:
    image: busybox
    container_name: §§INSTANCE-xnat-data
    volumes:
      - ./var/lib/postgresql/data:/var/lib/postgresql/data
