version: '2'

networks:
    bibbox-default-network:
      external: true
      
services:

  §§INSTANCE-xnatweb:
    image: bibbox/xnatweb
    container_name:  §§INSTANCE-xnatweb
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-xnat-db:xnat-db
    ports:
      - "§§PORT:8080"
    depends_on:
      - §§INSTANCE-xnat-db
      - §§INSTANCE-xnat-data
    volumes_from: 
      - §§INSTANCE-xnat-data
    environment:   
       DB_HOST: xnat-db
       DB_NAME: xnat
       DB_USER: xnat
       DB_PASSWORD: §§POSTGRES_PASSWORD

  §§INSTANCE-xnat-db:
    image: postgres:9.6.5-alpine
    container_name: §§INSTANCE-xnat-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      -  POSTGRES_PASSWORD=§§POSTGRES_PASSWORD
      - POSTGRES_USER=xnat
      - POSTGRES_DB=xnat 
    volumes_from: 
      - §§INSTANCE-xnat-data
    depends_on:
      - §§INSTANCE-xnat-data

  §§INSTANCE-xnat-data:
    image: busybox
    container_name: §§INSTANCE-xnat-data
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/xnat:/data/xnat