version: '2'

networks:
    bibbox-default-network:
      external: true
      
services:

  DEV-xnat:
    build: ./images/xnatweb
    container_name:  DEV-xnat
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - DEV-xnat-db:xnat-db
    ports:
      - "§§PORT:80"
    depends_on:
      - DEV-xnat-db
      - DEV-xnat-data
    volumes_from: 
      - DEV-xnat-data
    environment:   
       DB_HOST: xnat-db
       DB_NAME: xnat
       DB_USER: xnat
       DB_PASSWORD: §§POSTGRES_PASSWORD

  DEV-xnat-db:
    build: ./images/postgres/
    container_name: DEV-xnat-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      -  POSTGRES_PASSWORD=§§POSTGRES_PASSWORD
    volumes_from: 
      - DEV-xnat-data
    depends_on:
      - DEV-xnat-data

  DEV-xnat-data:
    image: busybox
    container_name: DEV-xnat-data
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/xnat:/data/xnat
