version: '2'

networks:
    bibbox-default-network:
      external: true
      
services:

  dev-xnat:
    image: bibbox/xnatweb
    container_name:  dev-xnat-local
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - dev-xnat-db:xnat-db
    ports:
      - "8077:8080"
    environment:   
       DB_PASSWORD: newpassword__newpassword
    depends_on:
      - dev-xnat-db
      - dev-xnat-data
    volumes_from: 
      - dev-xnat-data

  dev-xnat-db:
    image: postgres:9.6.5-alpine
    container_name: dev-xnat-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    environment:
      - POSTGRES_PASSWORD=newpassword__newpassword
      - POSTGRES_USER=xnat
      - POSTGRES_DB=xnat 
    volumes_from: 
      - dev-xnat-data
    depends_on:
      - dev-xnat-data

  dev-xnat-data:
    image: busybox
    container_name: dev-xnat-data
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/xnat:/data/xnat
